// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkBB49f2b4A_udunXivFp9AMVXTzIOyE',
    appId: '1:21247948423:web:9aa792ece2d04a46d66a22',
    messagingSenderId: '21247948423',
    projectId: 'lactosafe-app',
    authDomain: 'lactosafe-app.firebaseapp.com',
    storageBucket: 'lactosafe-app.appspot.com',
    measurementId: 'G-ZG8QW0LP3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-RTMaAvyc1nJXr6EdEmzkUEwsvAfe0Jk',
    appId: '1:21247948423:android:411788e50ee9f0ebd66a22',
    messagingSenderId: '21247948423',
    projectId: 'lactosafe-app',
    storageBucket: 'lactosafe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGy5C_tM3TT8It3XI0ohlp9ptb04yLto',
    appId: '1:21247948423:ios:2ebff6a9d1113157d66a22',
    messagingSenderId: '21247948423',
    projectId: 'lactosafe-app',
    storageBucket: 'lactosafe-app.appspot.com',
    iosClientId: '21247948423-6b8bjalnq0bc2gof9plbefbe7lvqlf7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lactosafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALGy5C_tM3TT8It3XI0ohlp9ptb04yLto',
    appId: '1:21247948423:ios:2ebff6a9d1113157d66a22',
    messagingSenderId: '21247948423',
    projectId: 'lactosafe-app',
    storageBucket: 'lactosafe-app.appspot.com',
    iosClientId: '21247948423-6b8bjalnq0bc2gof9plbefbe7lvqlf7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lactosafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxkBB49f2b4A_udunXivFp9AMVXTzIOyE',
    appId: '1:21247948423:web:47757520a64b6be1d66a22',
    messagingSenderId: '21247948423',
    projectId: 'lactosafe-app',
    authDomain: 'lactosafe-app.firebaseapp.com',
    storageBucket: 'lactosafe-app.appspot.com',
    measurementId: 'G-M5HQG2TR9W',
  );
}
